version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: 'npm'
    # Look for `package.json` and `lock` files in the `root` directory
    directory: '/'
    schedule:
      interval: 'daily'
    ignore:
      - dependency-name: 'node-fetch'
        # For node-fetch, ignore all updates for version 3
        versions: ['3.x']
      - dependency-name: 'redis'
        # For redis, ignore all updates for version 4
        versions: ['4.x']