name: CI_AutoMerge_Dependabot

on:
  pull_request:
    paths-ignore: # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet
      - '**/README.md'
      - '**/dependabot.yml'
    branches:
      - develop

jobs:
  build:
    uses: IATI/.github/.github/workflows/build_node_save.yaml@main
    with:
      npm_version: ^10
      save_artifact: false

  automerge:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: fastify/github-action-merge-dependabot@v3.0.2
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
