name: Deploy_To_Prod_Function_On_Release

on:
  release:
    types: [published]

env:
  STAGE: PROD # suffix to indicate environment stage
  NAME: func-iati-sitemapper
  SOLR_API_URL: ${{ secrets.PROD_SOLR_API_URL }}
  SOLR_USER: ${{ secrets.PROD_SOLR_NOADMIN_USER }}
  SOLR_PASSWORD: ${{ secrets.PROD_SOLR_NOADMIN_PASSWORD }}
  DDS_FRONTEND_URL: ${{ secrets.PROD_DDS_FRONTEND_URL }}
  REDIS_HOSTNAME: ${{ secrets.PROD_REDIS_HOSTNAME }}
  REDIS_PORT: ${{ secrets.REDIS_PORT }}
  REDIS_KEY: ${{ secrets.PROD_REDIS_KEY }}
  KV_URI: ${{ secrets.PROD_KV_URI }}
  VALIDATOR_FRONTEND_URL: ${{ secrets.PROD_VALIDATOR_FRONTEND_URL }}
  VALIDATOR_SERVICES_API_URL: ${{ secrets.PROD_VALIDATOR_SERVICES_URL }}
  VALIDATOR_SERVICES_API_KEY_NAME: ${{ secrets.PROD_VALIDATOR_SERVICES_KEY_NAME }}
  VALIDATOR_SERVICES_API_KEY_VALUE: ${{ secrets.PROD_VALIDATOR_SERVICES_KEY_VALUE }}

jobs:
  build_save:
    uses: IATI/.github/.github/workflows/build_node_save.yaml@main
    with:
      npm_version: ^10      
      save_artifact: true
      artifact_name: build-artifact-prod

  deploy:
    needs: build_save
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact-prod

      - name: Unzip build artifact
        run: |
          unzip build-artifact-prod.zip
          rm build-artifact-prod.zip

      - name: 'Login via Azure CLI'
        uses: azure/login@v1.4.3
        with:
          creds: ${{ secrets.PROD_AZURE_CREDENTIALS }} # Service Principal credentials saved in GitHub Secrets

      - name: Set Env variables for connecting to DSS API instance
        uses: Azure/appservice-settings@v1.1.1
        with:
          app-name: ${{env.NAME}}-${{env.STAGE}}
          app-settings-json: |
            [
                {
                    "name": "WEBSITE_NODE_DEFAULT_VERSION",
                    "value": "~16",
                    "slotSetting": false
                },
                {
                    "name": "SOLR_API_URL",
                    "value": "${{ env.SOLR_API_URL }}",
                    "slotSetting": false
                },
                {
                    "name": "SOLR_USER",
                    "value": "${{ env.SOLR_USER }}",
                    "slotSetting": false
                },
                {
                    "name": "SOLR_PASSWORD",
                    "value": "${{ env.SOLR_PASSWORD }}",
                    "slotSetting": false
                },
                {
                    "name": "DDS_FRONTEND_URL",
                    "value": "${{ env.DDS_FRONTEND_URL }}",
                    "slotSetting": false
                },
                {
                    "name": "REDIS_HOSTNAME",
                    "value": "${{ env.REDIS_HOSTNAME }}",
                    "slotSetting": false
                },
                {
                    "name": "REDIS_KEY",
                    "value": "${{ env.REDIS_KEY }}",
                    "slotSetting": false
                },
                {
                    "name": "REDIS_PORT",
                    "value": "${{ env.REDIS_PORT }}",
                    "slotSetting": false
                },
                {
                    "name": "AzureWebJobsSecretStorageType",
                    "value": "keyvault",
                    "slotSetting": false
                },
                {
                    "name": "AzureWebJobsSecretStorageKeyVaultUri",
                    "value": "${{ env.KV_URI }}",
                    "slotSetting": false
                },
                {
                    "name": "VALIDATOR_FRONTEND_URL",
                    "value": "${{ env.VALIDATOR_FRONTEND_URL }}",
                    "slotSetting": false
                },
                {
                    "name": "VALIDATOR_SERVICES_API_URL",
                    "value": "${{ env.VALIDATOR_SERVICES_API_URL }}",
                    "slotSetting": false
                },
                {
                    "name": "VALIDATOR_SERVICES_API_KEY_NAME",
                    "value": "${{ env.VALIDATOR_SERVICES_API_KEY_NAME }}",
                    "slotSetting": false
                },
                {
                    "name": "VALIDATOR_SERVICES_API_KEY_VALUE",
                    "value": "${{ env.VALIDATOR_SERVICES_API_KEY_VALUE }}",
                    "slotSetting": false
                }
            ]

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1.4.4
        with:
          app-name: ${{ env.NAME }}-${{ env.STAGE }}

  integration-test:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2.4.0

      - name: 'Install newman'
        run: |
          sudo npm i -g newman

      - name: 'Run integration tests' # Update -e environment file with an environment that points to your deployed instance
        run: |
          newman run integration-tests/func-iati-sitemapper.postman_collection.json -e integration-tests/envs/prod.postman_environment.json --working-dir integration-tests/test-files
